# Generated by Django 2.0.3 on 2018-03-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmin', models.IntegerField(default=0)),
                ('vmax', models.IntegerField(default=800)),
                ('vcc', models.IntegerField(default=3300)),
                ('pw', models.IntegerField(default=50)),
                ('t', models.IntegerField(default=100)),
                ('a', models.IntegerField(default=50)),
                ('e', models.IntegerField(default=10)),
                ('loop', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=10, unique=True)),
                ('passwd', models.CharField(blank=True, max_length=8)),
                ('command', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('done_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'done')], default='1', max_length=1)),
                ('ri', models.CharField(blank=True, max_length=6000, null=True)),
                ('rv', models.CharField(blank=True, max_length=6000, null=True)),
                ('command', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.Command')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Team'),
        ),
    ]
