# Generated by Django 2.0.3 on 2018-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180407_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentresult',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
